#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  🚨 ORAVINI.COM QUICK FIX 🚨                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Your site is DOWN because DATABASE_URL is missing on Render."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OPTION 1: Use render.yaml (EASIEST - RECOMMENDED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click: 'New +' → 'Blueprint'"
echo "3. Connect your GitHub repo: aryan07surana-hub/Oravini"
echo "4. Render will read render.yaml and create EVERYTHING automatically"
echo "5. Wait 5 minutes → Your site will be LIVE! ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  OPTION 2: Manual Setup (if you already have services)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create PostgreSQL database:"
echo "   → https://dashboard.render.com → New + → PostgreSQL"
echo "   → Name: oravini-db"
echo "   → Copy the 'External Database URL'"
echo ""
echo "2. Add to your web service:"
echo "   → Go to your 'oravini' service → Environment tab"
echo "   → Add: DATABASE_URL = <paste the URL>"
echo "   → Add: SESSION_SECRET = oravini-secret-2024-xyz"
echo "   → Add: APP_URL = https://oravini.com"
echo "   → Save → Wait 3 minutes → DONE! ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  After Site is Live:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run database migrations:"
echo "  → Render Dashboard → Your service → Shell tab"
echo "  → Run: npm install && npx drizzle-kit push"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Full guide: cat DEPLOYMENT_FIX.md"
echo ""
