services:
  - type: web
    name: oravini
    runtime: node
    buildCommand: npm install --include=dev && node script/build.mjs
    startCommand: NODE_ENV=production node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.22.0
